export const SEARCH_ACTION_TYPES = {
    GET_GIF_DATA_START:'GET_GIF_DATA_START',
    GET_GIF_DATA_SUCCESS:'GET_GIF_DATA_SUCCESS',
    GET_GIF_DATA_FAILURE:'GET_GIF_DATA_FAILURE',
    GET_DEFAULT:'GET_DEFAULT',
}